# Generated by Django 3.1.3 on 2021-01-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alunoTreino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.CharField(max_length=256)),
                ('done', models.CharField(choices=[('done', 'DONE'), ('doing', 'DOING')], max_length=5)),
                ('Created_at', models.DateField(auto_now_add=True)),
                ('upptead_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
